### ISSUE TITLE
Rover's Write to the same log file

### ISSUE THREAD

**Issue by pieckle** [Van-Bossuyt-Research-Lab/SPEARS_Simulator#28]
Multiple rovers of the same type (same name) all write to the same file in the generated logs folder.

> Using Mentality: {1.0; 20.0; 2.0; 0.3; 7.0; }		[04/28/2017 02:35:52.99]
> time	X	Y	Z	score	state	hazard		[04/28/2017 02:35:52.99]
> Using Mentality: {2.0; 5.0; 4.0; 2.0; 8.0; }		[04/28/2017 02:35:52.99]
> time	X	Y	Z	score	state	hazard		[04/28/2017 02:35:52.99]

**Comment by zmimlitz** [comment]
Unique rover names were not being passed to the autonomous code model named under the generalize architecture, which cause them to have the same log filename.  SOLVED: by having all autonomous code models informed of the name of the platform they were operating on and while at it, generalized the logging code to all code model derivatives.  #31
