### ISSUE TITLE
Massive Stack Traces on Computer with no Sound

### ISSUE THREAD

**Issue by pieckle** [Van-Bossuyt-Research-Lab/SPEARS_Simulator#29]
My computer has no sound card so there are massive stack traces in the console output but the program doesn't fail.

> 14:23:37.750 [AWT-EventQueue-0] ERROR com.spears.ui.sound.SoundPlayer - Sound Failed to Play
> java.io.IOException: mark/reset not supported
>         at java.util.zip.InflaterInputStream.reset(InflaterInputStream.java:286) ~[?:1.8.0_20]
>         at java.io.FilterInputStream.reset(FilterInputStream.java:226) ~[?:1.8.0_20]
>         at com.sun.media.sound.SoftMidiAudioFileReader.getAudioInputStream(SoftMidiAudioFileReader.java:135) ~[?:1.8.0_20]
>         at javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:1113) ~[?:1.8.0_20]
>         at com.spears.ui.sound.SoundPlayer.playSound(SoundPlayer.java:64) [SPEARS.jar:?]
>         at com.spears.ui.implementation.PopUpImpl.lambda$initialize$105(PopUpImpl.java:70) [SPEARS.jar:?]
>         at com.spears.ui.implementation.PopUpImpl$$Lambda$64/512549200.actionPerformed(Unknown Source) [SPEARS.jar:?]
>         at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) [?:1.8.0_20]
>         at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346) [?:1.8.0_20]
>         at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) [?:1.8.0_20]
>         at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) [?:1.8.0_20]
>         at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) [?:1.8.0_20]
>         at java.awt.Component.processMouseEvent(Component.java:6525) [?:1.8.0_20]
>         at javax.swing.JComponent.processMouseEvent(JComponent.java:3321) [?:1.8.0_20]
>         at java.awt.Component.processEvent(Component.java:6290) [?:1.8.0_20]
>         at java.awt.Container.processEvent(Container.java:2234) [?:1.8.0_20]
>         at java.awt.Component.dispatchEventImpl(Component.java:4881) [?:1.8.0_20]
>         at java.awt.Container.dispatchEventImpl(Container.java:2292) [?:1.8.0_20]
>         at java.awt.Component.dispatchEvent(Component.java:4703) [?:1.8.0_20]
>         at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898) [?:1.8.0_20]
>         at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533) [?:1.8.0_20]
>         at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462) [?:1.8.0_20]
>         at java.awt.Container.dispatchEventImpl(Container.java:2278) [?:1.8.0_20]
>         at java.awt.Window.dispatchEventImpl(Window.java:2739) [?:1.8.0_20]
>         at java.awt.Component.dispatchEvent(Component.java:4703) [?:1.8.0_20]
>         at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746) [?:1.8.0_20]
>         at java.awt.EventQueue.access$400(EventQueue.java:97) [?:1.8.0_20]
>         at java.awt.EventQueue$3.run(EventQueue.java:697) [?:1.8.0_20]
>         at java.awt.EventQueue$3.run(EventQueue.java:691) [?:1.8.0_20]
>         at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_20]
>         at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) [?:1.8.0_20]
>         at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86) [?:1.8.0_20]
>         at java.awt.EventQueue$4.run(EventQueue.java:719) [?:1.8.0_20]
>         at java.awt.EventQueue$4.run(EventQueue.java:717) [?:1.8.0_20]
>         at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_20]
>         at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) [?:1.8.0_20]
>         at java.awt.EventQueue.dispatchEvent(EventQueue.java:716) [?:1.8.0_20]
>         at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_20]
>         at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_20]
>         at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_20]
>         at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_20]
>         at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_20]
>         at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_20]

**Comment by zmimlitz** [comment]
Verified that the problem persists on computers with sound: problem with packaging

**Comment by zmimlitz** [comment]
Problem detailed in [this post](http://stackoverflow.com/questions/5529754/java-io-ioexception-mark-reset-not-supported).  Pretty easy fix.  #32
